const ACTIONS = {
  ADD_TAG: 'ADD_TAG',
  CREATE_AUTHOR_FOR_POST: 'CREATE_AUTHOR_FOR_POST',
  CREATE_POST: 'CREATE_POST',
  DELETE_POST: 'DELETE_POST',
  POST_DELETED: 'POST_DELETED',
  POST_REQUEST_FAILED: 'POST_REQUEST_FAILED',
  RECEIVE_POST_PAGE: 'RECEIVE_POST_PAGE',
  RECEIVE_POSTS: 'RECEIVE_POSTS',
  REMOVE_AUTHOR: 'REMOVE_AUTHOR',
  REMOVE_TAG: 'REMOVE_TAG',
  REQUEST_POST: 'REQUEST_POST',
  REQUEST_POST_PAGE: 'REQUEST_POST_PAGE',
  REQUEST_POSTS: 'REQUEST_POSTS',
  REQUEST_POSTS_FOR_AUTHOR: 'REQUEST_POSTS_FOR_AUTHOR',
  REQUEST_POSTS_FOR_TAG: 'REQUEST_POSTS_FOR_TAG',
  SET_POST_AUTHOR: 'SET_POST_AUTHOR',
  TRANSITION_POST: 'TRANSITION_POST',
  UPDATE_POST: 'UPDATE_POST',
}

export default ACTIONS
