const ACTIONS = {
  RECEIVE_NEWSLETTER_SUBSCRIPTION: 'RECEIVE_NEWSLETTER_SUBSCRIPTION',
  SOCIAL_REQUEST_FAILED: 'SOCIAL_REQUEST_FAILED',
  SUBSCRIBE_TO_NEWSLETTER: 'SUBSCRIBE_TO_NEWSLETTER',
}

export default ACTIONS
