const ACTIONS = {
  AUTHORS_REQUEST_FAILED: 'AUTHORS_REQUEST_FAILED',
  CREATE_AUTHOR: 'CREATE_AUTHOR',
  RECEIVE_AUTHOR_PROFILE: 'RECEIVE_AUTHOR_PROFILE',
  RECEIVE_AUTHORS: 'RECEIVE_AUTHORS',
  RECEIVE_AUTHORS_PAGE: 'RECEIVE_AUTHORS_PAGE',
  REQUEST_AUTHOR: 'REQUEST_AUTHOR',
  REQUEST_AUTHORS: 'REQUEST_AUTHORS',
  REQUEST_AUTHORS_PAGE: 'REQUEST_AUTHORS_PAGE',
  UPDATE_AUTHOR: 'UPDATE_AUTHOR',
}

export default ACTIONS
