const ACTIONS = {
  FETCH_CURRENT_USER: 'FETCH_CURRENT_USER',
  RECEIVE_USERS: 'RECEIVE_USERS',
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  SIGN_IN_GOOGLE_ACCOUNT: 'SIGN_IN_GOOGLE_ACCOUNT',
  USERS_REQUEST_FAILED: 'USERS_REQUEST_FAILED',
}

export default ACTIONS
