const ACTIONS = {
  ADD_AUTHOR_PROFILE: 'ADD_AUTHOR_PROFILE',
  AUTHOR_PROFILE_DELETED: 'AUTHOR_PROFILE_DELETED',
  DELETE_AUTHOR_PROFILE: 'DELETE_AUTHOR_PROFILE',
  PROFILES_REQUEST_FAILED: 'PROFILES_REQUEST_FAILED',
  RECEIVE_PROFILES: 'RECEIVE_PROFILES',
  UPDATE_PROFILE: 'UPDATE_PROFILE',
}

export default ACTIONS
