const ACTIONS = {
  CHANGE: 'CHANGE',
  CLEAR_ACTIVE_NODE: 'CLEAR_ACTIVE_NODE',
  EDIT_SUBTREE: 'EDIT_SUBTREE',
  EDITOR_REQUEST_FAILED: 'EDITOR_REQUEST_FAILED',
  FINISH_SUBTREE_EDIT: 'FINISH_SUBTREE_EDIT',
  RECEIVE_NODES: 'RECEIVE_NODES',
  RECEIVE_POST_BODY: 'RECEIVE_POST_BODY',
  REPORT_UPLOAD_COMPLETE: 'REPORT_UPLOAD_COMPLETE',
  REPORT_UPLOAD_STATUS: 'REPORT_UPLOAD_STATUS',
  REQUEST_NODE: 'REQUEST_NODE',
  REQUEST_POST_BODY: 'REQUEST_POST_BODY',
  SAVE_POST_BODY: 'SAVE_POST_BODY',
  SET_ACTIVE_NODE: 'SET_ACTIVE_NODE',
  SUBSCRIBE_TO_UPLOAD_JOB: 'SUBSCRIBE_TO_UPLOAD_JOB',
}

export default ACTIONS
