const ACTIONS = {
  CREATE_TAG: 'CREATE_TAG',
  RECEIVE_TAGS: 'RECEIVE_TAGS',
  RECEIVE_TAGS_PAGE: 'RECEIVE_TAGS_PAGE',
  REQUEST_TAG: 'REQUEST_TAG',
  REQUEST_TAGS: 'REQUEST_TAGS',
  REQUEST_TAGS_PAGE: 'REQUEST_TAGS_PAGE',
  TAGS_REQUEST_FAILED: 'TAGS_REQUEST_FAILED',
  UPDATE_TAG: 'UPDATE_TAG',
}

export default ACTIONS
